---
# roles/mysql_setup/defaults/main.yml
mysql_version: "10.4"
ip_hostname_mapping:
      - { ip: '172.16.1.16', hostname: 'web01' }
      - { ip: '172.16.1.17', hostname: 'app01' }
      - { ip: '172.16.1.18', hostname: 'rmq01' }
      - { ip: '172.16.1.19', hostname: 'mc01' }
      - { ip: '172.16.1.20', hostname: 'db01' }
      - { ip: '172.16.1.167', hostname: 'tfdhomesvr' }
# defaults file for roles/mysql_setup