---
- hosts: app01
  gather_facts: true
  become: true
  vars:
    - ip_hostname_mapping:
      - { ip: '172.16.1.16', hostname: 'web01' }
      - { ip: '172.16.1.17', hostname: 'app01' }
      - { ip: '172.16.1.18', hostname: 'rmq01' }
      - { ip: '172.16.1.19', hostname: 'mc01' }
      - { ip: '172.16.1.20', hostname: 'db01' }
      - { ip: '172.16.1.167', hostname: 'tfdhomesvr' }

  tasks:
    - name: Update yum cache
      ansible.builtin.yum:
        update_cache: yes
    
    - name: Update System with latest packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Check if EPEL repo is installed
      ansible.builtin.command: 'yum repolist enabled | grep epel'
      register: epel_check
      ignore_errors: true
      changed_when: false

    - name: Ensure EPEL Repository is installed
      ansible.builtin.yum:
        name: 'epel-release'
        state: present
      when: epel_check.rc != 0  
        